<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gerenciador_asssinantes_plataforma_digital.Domain\Gerenciador_asssinantes_plataforma_digital.Domain.csproj" />
  </ItemGroup>

</Project>
