<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ContainerRuntimeIdentifier>win-x64</ContainerRuntimeIdentifier>
    <EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-1809</ContainerBaseImage>
    <UserSecretsId>7e339c63-1c47-4a43-b4a3-802046306ee9</UserSecretsId>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ContainerPort Include="8081" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gerenciador_asssinantes_plataforma_digital.Application\Gerenciador_asssinantes_plataforma_digital.Application.csproj" />
    <ProjectReference Include="..\Gerenciador_asssinantes_plataforma_digital.Infrastructure\Gerenciador_asssinantes_plataforma_digital.Infrastructure.csproj" />
  </ItemGroup>

</Project>
